# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: chris.house
email: me@chris.house
description: > # this means to ignore newlines until "baseurl:"
  Chris House is a web designer and front-end developer from Kansas City.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chrishouse83
github_username:  chrishouse 

# Build settings
markdown: kramdown
